/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-13 03:00:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/WebDevelopment/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CarCamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/../bottom.jsp", Long.valueOf(1657680793257L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655811683348L));
    _jspx_dependants.put("/WEB-INF/views/admin/left.jsp", Long.valueOf(1657680793247L));
    _jspx_dependants.put("/WEB-INF/views/admin/adminTop.jsp", Long.valueOf(1657680793243L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"TemplateMo\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("<!-- 프로필 오프캔버스 -->\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("   integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\"\r\n");
      out.write("   integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>WithCar HomePage</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Additional CSS Files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/fontawesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/templatemo-edu-meeting.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/owl.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/lightbox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/map_region.css\">\r\n");
      out.write("\r\n");
      out.write("<!--바케성 0613 배너 css js-->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".has-sub>.sub-menu>a{\r\n");
      out.write("background: transparent;\r\n");
      out.write("}\r\n");
      out.write(".has-sub>.sub-menu>li{\r\n");
      out.write("border :1px solid black;\r\n");
      out.write("}\r\n");
      out.write(".has-sub>.sub-menu{.\r\n");
      out.write("background: transparent;\r\n");
      out.write("padding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-group-flush > a : hover{\r\n");
      out.write("background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".floating {\r\n");
      out.write("  position: fixed; \r\n");
      out.write("  right: 37%; \r\n");
      out.write("  top: 55%; \r\n");
      out.write("  margin-right: -680px;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  width: 120px;\r\n");
      out.write("}   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- ***** Header Area Start ***** -->\r\n");
      out.write("   <header class=\"header-area header-sticky\" style=\"background-color : #FFFFFF\"><!-- 색깔 바꾸기 -->\r\n");
      out.write("      <div class=\"container\" style=\"height: 90px\";>   \r\n");
      out.write("         <div class=\"row\" style=\"height: 90px\";>\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("               <nav class=\"main-nav\">\r\n");
      out.write("                  <!-- ***** Logo Start ***** -->\r\n");
      out.write("                  <a href=\"index.do\" class=\"logo\" style=\"height: 90px;\"><img src=\"resources/images/withcar.png\" style=\"width: 170px;height: 70px;\"/></a>\r\n");
      out.write("                  <!-- ***** Logo End ***** -->\r\n");
      out.write("                  <!-- ***** Menu Start ***** -->\r\n");
      out.write("                  <ul class=\"nav\">\r\n");
      out.write("                     <li ><a  href=\"index.do\"><svg  xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-house-door-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                       <path d=\"M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z\"/>\r\n");
      out.write("                     </svg></a></li>\r\n");
      out.write("                     <li class=\"has-sub\"><a href=\"javascript:void(0)\">바로가기</a>\r\n");
      out.write("                        <ul class=\"sub-menu\" >\r\n");
      out.write("                           <li><a href=\"goRegion.region\"  style=\"background: transparent;\">차박지 메인</a></li>\r\n");
      out.write("                           <li><a href=\"goProduct.product\"  style=\"background: transparent;\">용품 대여</a></li>\r\n");
      out.write("                        </ul></li>\r\n");
      out.write("                     \r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <a class='menu-trigger'> <span>Menu</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <!-- ***** Menu End ***** -->\r\n");
      out.write("               </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"floating\">\r\n");
      out.write("          <img src=\"resources/images/warning.png\" onclick=\"location.href='uesrAnnounce.admin'\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   <section>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <!-- ***** Header Area End ***** -->");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- Container -->\r\n");
      out.write("<head>\r\n");
      out.write("	<!-- rating -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/rating.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("<!-- <script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid themed-container\">\r\n");
      out.write("	<!-- Row Grid -->\r\n");
      out.write("	<div class=\"row justify-content-md-center\">\r\n");
      out.write("    <!-- List Column Grid -->\r\n");
      out.write("	<div class=\"d-flex flex-column flex-shrink-0 p-3 bg-light text-center\" style=\"width: 250px; height: 700px;\">\r\n");
      out.write("    <a href=\"goAdmin.admin\" class=\"sidebar-heading border-bottom bg-light\">\r\n");
      out.write("      <use xlink:href=\"#bootstrap\"></use></svg>\r\n");
      out.write("      <span class=\"fs-4\"><b>관리자 페이지</b></span>\r\n");
      out.write("    </a>\r\n");
      out.write("     <br>\r\n");
      out.write("    <ul class=\"nav nav-pills flex-column mb-auto\">\r\n");
      out.write("    \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminRegion.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3\" aria-current=\"page\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#home\"></use></svg> \r\n");
      out.write("         \r\n");
      out.write("      차박 장소 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminAgency.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#speedometer2\"></use></svg>\r\n");
      out.write("         \r\n");
      out.write("      대리점 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write(" \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminCategory.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#table\"></use></svg>\r\n");
      out.write("        \r\n");
      out.write("     카테고리 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminProduct.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#grid\"></use></svg>\r\n");
      out.write("         \r\n");
      out.write("        차박 용품 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminMember.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("          \r\n");
      out.write("   회원 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminReviewRegion.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("        \r\n");
      out.write("  장소 리뷰 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminReviewProduct.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("         \r\n");
      out.write("  용품 리뷰 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminAnnounce.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-leftr\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("         \r\n");
      out.write("         공지사항 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminQuestion.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("        \r\n");
      out.write("         문의사항 관리\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"adminRental.admin\" class=\"list-group-item list-group-item-action list-group-item-light p-3 text-left\">\r\n");
      out.write("          <svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("        \r\n");
      out.write("         대여현황\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- //////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"col-md-8 themed-grid-col\" style=\"padding-left: 20px;padding-right: 20px;\">\r\n");
      out.write("      <img src=\"resources/images/adminMain.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<div id=\"hd\">\r\n");
      out.write("<div class=\"banner_slide\"> <!--바케성 0613 배너  -->\r\n");
      out.write("   <div class=\"card text-center\"> \r\n");
      out.write("      <div class=\"card-body\" >\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <img src=\"resources/images/banner_bottom1.jpg\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"card text-center\">\r\n");
      out.write("      <div class=\"card-body\" >\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <img src=\"resources/images/banner_bottom2.jpg\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"card text-center\">\r\n");
      out.write("      <div class=\"card-body\" >\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <img src=\"resources/images/banner_bottom3.jpg\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"card text-center\"> \r\n");
      out.write("      <div class=\"card-body\" >\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <img src=\"resources/images/banner_bottom4.jpg\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"card text-center\"> \r\n");
      out.write("      <div class=\"card-body\" >\r\n");
      out.write("         <a href=\"#\">\r\n");
      out.write("            <img src=\"resources/images/banner_bottom5.jpg\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\"\r\n");
      out.write("   style=\"padding-bottom: 0px; margin-top: 0px; padding-top: 0px;\">\r\n");
      out.write("   <p\r\n");
      out.write("      style=\"background-color: #2c3e50; color: #fff; margin-bottom: 0px;\">\r\n");
      out.write("      Copyright © 2022 <a href=\"#\">WITHCAR Co.</a> Ltd. All Rights Reserved.\r\n");
      out.write("      <br> Design: <a href=\"#\">WITHCAR DESIGN TEAM</a> <br> MADE\r\n");
      out.write("      BY: <a href=\"#\">WITHCAR TEAM</a>\r\n");
      out.write("   </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 바케성0613 배너 js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"></script> -->\r\n");
      out.write("<!--   <script src=\"resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<script src=\"resources/js/isotope.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/owl-carousel.js\"></script>\r\n");
      out.write("<script src=\"resources/js/lightbox.js\"></script>\r\n");
      out.write("<script src=\"resources/js/tabs.js\"></script>\r\n");
      out.write("<script src=\"resources/js/video.js\"></script>\r\n");
      out.write("<script src=\"resources/js/slick-slider.js\"></script>\r\n");
      out.write("<script src=\"resources/js/custom.js\"></script>   \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    \r\n");
      out.write("        //according to loftblog tut\r\n");
      out.write("        $('.nav li:first').addClass('active');\r\n");
      out.write("\r\n");
      out.write("        var showSection = function showSection(section, isAnimate) {\r\n");
      out.write("          var\r\n");
      out.write("          direction = section.replace(/#/, ''),\r\n");
      out.write("          reqSection = $('.section').filter('[data-section=\"' + direction + '\"]'),\r\n");
      out.write("          reqSectionPos = reqSection.offset().top - 0;\r\n");
      out.write("\r\n");
      out.write("          if (isAnimate) {\r\n");
      out.write("            $('body, html').animate({\r\n");
      out.write("              scrollTop: reqSectionPos },\r\n");
      out.write("            800);\r\n");
      out.write("          } else {\r\n");
      out.write("            $('body, html').scrollTop(reqSectionPos);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var checkSection = function checkSection() {\r\n");
      out.write("          $('.section').each(function () {\r\n");
      out.write("            var\r\n");
      out.write("            $this = $(this),\r\n");
      out.write("            topEdge = $this.offset().top - 80,\r\n");
      out.write("            bottomEdge = topEdge + $this.height(),\r\n");
      out.write("            wScroll = $(window).scrollTop();\r\n");
      out.write("            if (topEdge < wScroll && bottomEdge > wScroll) {\r\n");
      out.write("              var\r\n");
      out.write("              currentId = $this.data('section'),\r\n");
      out.write("              reqLink = $('a').filter('[href*=\\#' + currentId + ']');\r\n");
      out.write("              reqLink.closest('li').addClass('active').\r\n");
      out.write("              siblings().removeClass('active');\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {\r\n");
      out.write("          e.preventDefault();\r\n");
      out.write("          showSection($(this).attr('href'), true);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("          checkSection();\r\n");
      out.write("        });\r\n");
      out.write("        /*바케성 0613 배너추가  */\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $('.banner_slide').slick({\r\n");
      out.write("               slide: 'div',      //슬라이드 되어야 할 태그 ex) div, li \r\n");
      out.write("            infinite : true,    //무한 반복 옵션    \r\n");
      out.write("            slidesToShow : 1,      // 한 화면에 보여질 컨텐츠 개수\r\n");
      out.write("            slidesToScroll : 1,      //스크롤 한번에 움직일 컨텐츠 개수\r\n");
      out.write("            speed : 2000,    // 다음 버튼 누르고 다음 화면 뜨는데까지 걸리는 시간(ms)\r\n");
      out.write("            arrows : false,       // 옆으로 이동하는 화살표 표시 여부\r\n");
      out.write("            dots : false,       // 스크롤바 아래 점으로 페이지네이션 여부\r\n");
      out.write("            autoplay : true,         // 자동 스크롤 사용 여부\r\n");
      out.write("            autoplaySpeed : 3000,       // 자동 스크롤 시 다음으로 넘어가는데 걸리는 시간 (ms)\r\n");
      out.write("            pauseOnHover : false,      // 슬라이드 이동   시 마우스 호버하면 슬라이더 멈추게 설정\r\n");
      out.write("            vertical : false,      // 세로 방향 슬라이드 옵션\r\n");
      out.write("            /* prevArrow : \"<button type='button' class='slick-prev'>Previous</button>\",      // 이전 화살표 모양 설정\r\n");
      out.write("            nextArrow : \"<button type='button' class='slick-next'>Next</button>\",      // 다음 화살표 모양 설정\r\n");
      out.write("            dotsClass : \"slick-dots\",    //아래 나오는 페이지네이션(점) css class 지정 */\r\n");
      out.write("            draggable : true,    //드래그 가능 여부 \r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
