/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-21 11:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.region;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regionHotLocList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/region/regionMainBottom.jsp", Long.valueOf(1655808526333L));
    _jspx_dependants.put("jar:file:/C:/WebDevelopment/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CarCamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655811683348L));
    _jspx_dependants.put("/WEB-INF/views/region/../bottom.jsp", Long.valueOf(1655808526324L));
    _jspx_dependants.put("/WEB-INF/views/region/../top.jsp", Long.valueOf(1655808526335L));
    _jspx_dependants.put("/WEB-INF/views/region/regionMainTop.jsp", Long.valueOf(1655808526333L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"TemplateMo\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("<!-- 프로필 오프캔버스 -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>WithCar HomePage</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Additional CSS Files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/fontawesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/templatemo-edu-meeting.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/owl.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/lightbox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/map_region.css\">\r\n");
      out.write("\r\n");
      out.write("<!--바케성 0613 배너 css js-->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("<script>\r\n");
      out.write("	function field_review(){\r\n");
      out.write("		let signIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${signIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		if (signIn ==\"\"){\r\n");
      out.write("			alert(\"리뷰 쓰기는 로그인 후 사용하실 수 있습니다.\");\r\n");
      out.write("			location.href=\"login.login\";\r\n");
      out.write("			\r\n");
      out.write("		}else{\r\n");
      out.write("			location.href=\"field_review.review\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function goods_review(){\r\n");
      out.write("		let signIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${signIn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		if (signIn ==\"\"){\r\n");
      out.write("			alert(\"리뷰 쓰기는 로그인 후 사용하실 수 있습니다.\");\r\n");
      out.write("			location.href=\"login.login\";\r\n");
      out.write("			\r\n");
      out.write("		}else{\r\n");
      out.write("			location.href=\"goods_review.review\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".has-sub>.sub-menu>a{\r\n");
      out.write("background: transparent;\r\n");
      out.write("}\r\n");
      out.write(".has-sub>.sub-menu>li{\r\n");
      out.write("border :1px solid black;\r\n");
      out.write("}\r\n");
      out.write(".has-sub>.sub-menu{.\r\n");
      out.write("background: transparent;\r\n");
      out.write("padding-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- ***** Header Area Start ***** -->\r\n");
      out.write("	<header class=\"header-area header-sticky\" style=\"background-color : #FFFFFF\"><!-- 색깔 바꾸기 -->\r\n");
      out.write("		<div class=\"container\" style=\"height: 90px\";>	\r\n");
      out.write("			<div class=\"row\" style=\"height: 90px\";>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<nav class=\"main-nav\">\r\n");
      out.write("						<!-- ***** Logo Start ***** -->\r\n");
      out.write("						<a href=\"index.do\" class=\"logo\" style=\"height: 90px;\"><img src=\"resources/images/withcar.png\" style=\"width: 170px;height: 70px;\"/></a>\r\n");
      out.write("						<!-- ***** Logo End ***** -->\r\n");
      out.write("						<!-- ***** Menu Start ***** -->\r\n");
      out.write("						<ul class=\"nav\">\r\n");
      out.write("							<li ><a  href=\"index.do\"><svg  xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-house-door-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  							<path d=\"M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z\"/>\r\n");
      out.write("							</svg></a></li>\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							<li class=\"has-sub\"><a href=\"javascript:void(0)\">바로가기</a>\r\n");
      out.write("								<ul class=\"sub-menu\" >\r\n");
      out.write("									<li><a href=\"goRegion.region\"  style=\"background: transparent;\">차박지 메인</a></li>\r\n");
      out.write("									<li><a href=\"goProduct.product\"  style=\"background: transparent;\">용품 대여</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"has-sub\"><a href=\"javascript:void(0)\">리뷰쓰기</a>\r\n");
      out.write("							<ul class=\"sub-menu\" >\r\n");
      out.write("									<li><a style=\"background: transparent; \" onclick=\"field_review()\">장소 리뷰</a></li>\r\n");
      out.write("									<li><a style=\"background: transparent;\" onclick=\"goods_review()\">용품 리뷰</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li class=\"scroll-to-section\">\r\n");
      out.write("								<button class=\"btn btn-link\" data-bs-toggle=\"offcanvas\" href=\"#offcanvasExample\" aria-controls=\"offcanvasExample\"\r\n");
      out.write("								style=\"background-color: #091835;  color: #ffffff; text-decoration: none;\">\r\n");
      out.write("									프로필\r\n");
      out.write("								</button>\r\n");
      out.write("							</li>\r\n");
      out.write("				                <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\"\r\n");
      out.write("								id=\"offcanvasExample\" aria-labelledby=\"offcanvasExampleLabel\">\r\n");
      out.write("								<div class=\"offcanvas-header\">\r\n");
      out.write("									<h5 class=\"offcanvas-title\" id=\"offcanvasExampleLabel\"><b><font color=\"green\">내 메뉴</b></font></h5>\r\n");
      out.write("									<button type=\"button\" class=\"btn-close text-reset\"\r\n");
      out.write("										data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"offcanvas-body\">\r\n");
      out.write("									<div>\r\n");
      out.write("                                      <img src=\"sik.jpg\" class=\"card-img rounded-circle\"\r\n");
      out.write("						                style=\"width: 150px; height: 150px\" />\r\n");
      out.write("										닉네임/프로필사진\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"list-group\">\r\n");
      out.write("										<a href=\"myPageProfile.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">		\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											내 정보 </a> \r\n");
      out.write("										<a href=\"myPageWriteReview.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											내가 쓴 리뷰</a> \r\n");
      out.write("										<a href=\"myPageLikeReview.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											내가 좋아한 리뷰</a> \r\n");
      out.write("										<a href=\"myPageCart2.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											장바구니</a> \r\n");
      out.write("										<a href=\"myPageRental.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											대여내역</a>\r\n");
      out.write("										<a href=\"myPageContactUs.myPage\"\r\n");
      out.write("											class=\"list-group-item list-group-item-action list-group-item-light p-3\">\r\n");
      out.write("											<svg class=\"bi me-2\" width=\"16\" height=\"16\"><use xlink:href=\"#people-circle\"></use></svg>\r\n");
      out.write("											문의하기</a>	 \r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<a class='menu-trigger'> <span>Menu</span>\r\n");
      out.write("						</a>\r\n");
      out.write("						<!-- ***** Menu End ***** -->\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<section>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- ***** Header Area End ***** -->");
      out.write('\r');
      out.write('\n');
      out.write("<link rel=\"stylesheet\" href=\"assets/css/map_region.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function popup() {\r\n");
      out.write("		var url = \"regionReviewView.region\";\r\n");
      out.write("		var name = \"popup test\";\r\n");
      out.write("		var option = \"width = 700, height = 1000, top = 100, left = 200, location = no\"\r\n");
      out.write("		window.open(url, name, option);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ccm-doc-hs\" class=\"ccm-t7-hs\">\r\n");
      out.write("	<div id=\"ccm-bd-hs\">\r\n");
      out.write("		<div id=\"ccm-main-hs\">\r\n");
      out.write("			<div class=\"ccm-b-hs\">\r\n");
      out.write("				<div class=\"ccm-gc-hs\">\r\n");
      out.write("					<div class=\"ccm-u-hs first\">\r\n");
      out.write("						<div class=\"map_content-hs\">\r\n");
      out.write("							<div id=\"map\" class=\"border rounded-4 border-4\"\r\n");
      out.write("								style=\"width: 100%; height: 600px;\">\r\n");
      out.write("								<script type=\"text/javascript\"\r\n");
      out.write("									src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=a12f9fc709978bc3b122b007b64e2afd\"></script>\r\n");
      out.write("								<script>\r\n");
      out.write("									//맵생성\r\n");
      out.write("									var container = document\r\n");
      out.write("											.getElementById('map');\r\n");
      out.write("									var options = {\r\n");
      out.write("										center : new kakao.maps.LatLng(36, 128),\r\n");
      out.write("										level : 13,\r\n");
      out.write("										draggable : false,\r\n");
      out.write("										disableDoubleClick : true,\r\n");
      out.write("										disableDoubleClickZoom : true\r\n");
      out.write("									};\r\n");
      out.write("									var map = new kakao.maps.Map(container,\r\n");
      out.write("											options);\r\n");
      out.write("\r\n");
      out.write("									//좌표\r\n");
      out.write("									function Position(x, y) {\r\n");
      out.write("										this.x = x;\r\n");
      out.write("										this.y = y;\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("									var PositionArr = [\r\n");
      out.write("											new Position(37.540705, 126.956764),//서울=1\r\n");
      out.write("											//new Position(37.17, 127.7),//경기도\r\n");
      out.write("											new Position(37.8304115,\r\n");
      out.write("													128.2260705),//강원도 2 \r\n");
      out.write("											new Position(36.628503, 127.929344),//경상북도 5 \r\n");
      out.write("											new Position(36.557229, 126.779757),//경상남도 6 \r\n");
      out.write("											new Position(36.248647, 128.664734),//충청북도 3\r\n");
      out.write("											new Position(35.259787, 128.664734),//충청남도 4 \r\n");
      out.write("											new Position(35.716705, 127.144185),//전라북도 7 \r\n");
      out.write("											new Position(34.819400, 126.893113),//전라남도 8\r\n");
      out.write("											new Position(33.364805, 126.542671) //제주도=9\r\n");
      out.write("									];\r\n");
      out.write("\r\n");
      out.write("									//이미지\r\n");
      out.write("									//var imageSrc = 'mapMarkerImage/', //이미지 \r\n");
      out.write("									imageSize = new kakao.maps.Size(64, 69),\r\n");
      out.write("											imageOption = {\r\n");
      out.write("												offset : new kakao.maps.Point(\r\n");
      out.write("														27, 69)\r\n");
      out.write("											};\r\n");
      out.write("\r\n");
      out.write("									//var markerImage = new kakao.maps.MarkerImage(\r\n");
      out.write("									//		imageSrc, imageSize, imageOption);\r\n");
      out.write("\r\n");
      out.write("									//마커\r\n");
      out.write("									for (var i = 0; i < PositionArr.length; i++) {\r\n");
      out.write("										var markerPosition = new kakao.maps.LatLng(\r\n");
      out.write("												PositionArr[i].x,\r\n");
      out.write("												PositionArr[i].y);\r\n");
      out.write("										var imageSrc = \"resources/images/mapMarkerImage/\"\r\n");
      out.write("												+ (i + 1) + \".png\"\r\n");
      out.write("										var markerImage = new kakao.maps.MarkerImage(\r\n");
      out.write("												imageSrc, imageSize,\r\n");
      out.write("												imageOption);\r\n");
      out.write("\r\n");
      out.write("										addMarker(i);\r\n");
      out.write("									}\r\n");
      out.write("									//마커-클릭 이벤트 추가\r\n");
      out.write("									function addMarker(i) {\r\n");
      out.write("										var marker = new kakao.maps.Marker({\r\n");
      out.write("											map : map,\r\n");
      out.write("											position : markerPosition,\r\n");
      out.write("											image : markerImage,\r\n");
      out.write("											clickable : true\r\n");
      out.write("										});\r\n");
      out.write("										kakao.maps.event\r\n");
      out.write("												.addListener(\r\n");
      out.write("														marker,\r\n");
      out.write("														'click',\r\n");
      out.write("														function() {//해당지역 인기글 변경\r\n");
      out.write("															//window.location.href = \"goRegionHOT.region?region_num=\"+(i + 1);\r\n");
      out.write("															//window.location.href = \"goRegion.region?region_num=\"+ (i + 1);\r\n");
      out.write("															document.hotRegionLocation.region_num.value=i+1	\r\n");
      out.write("															document.hotRegionLocation.mem_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("															document.hotRegionLocation.submit()    \r\n");
      out.write("															\r\n");
      out.write("														});\r\n");
      out.write("									}\r\n");
      out.write("								</script> \r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form name=\"hotRegionLocation\" action=\"regionHotLocList.region\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"region_num\"/>\r\n");
      out.write("						<input type=\"hidden\" name=\"mem_id\"/>\r\n");
      out.write("					</form>\r\n");
      out.write("								\r\n");
      out.write("					<!--지역별 HOT리뷰글  -->\r\n");
      out.write("					<div class=\"ccm-u-hs border rounded-4 border-4\"\r\n");
      out.write("						style=\"height: 600px;\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"region_content-hs rounded-4 \">\r\n");
      out.write("	<ul class=\"list-group list-group-flush rounded-4 \">\r\n");
      out.write("\r\n");
      out.write("		<li class=\"list-group-item fs-2 text-center\"><button\r\n");
      out.write("				class=\"btn btn-outline-warning btn-lg\" type=\"button\" onclick=\"location.href='board.region?region_num=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regionDTO.region_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\"\r\n");
      out.write("				style=\"-bs-btn-padding-x: 70px; - -bs-btn-padding-y: 15px;\">\r\n");
      out.write("				<i class=\"bi bi-trophy-fill\" width=\"40\" height=\"40\"\r\n");
      out.write("					fill=\"currentColor\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regionDTO.region_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 차박지 더 많이 보기 <i\r\n");
      out.write("					class=\"bi bi-trophy-fill\" width=\"40\" height=\"40\"\r\n");
      out.write("					fill=\"currentColor\"></i>\r\n");
      out.write("			</button> ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("		<!--HOT차박지  -->\r\n");
      out.write("		<div class=\"ccm-b-hs\">\r\n");
      out.write("			<div id=\"hot-loaction-title-hs\" style=\"margin-top: 20px;\">\r\n");
      out.write("				<nav\r\n");
      out.write("					class=\"navbar navbar-expand-lg border rounded-4 border-4 aria-label=\"\r\n");
      out.write("					Eighth\r\n");
      out.write("					navbarexample\" \r\n");
      out.write("					style=\"margin-bottom: 0px; background-color: #dc3545d4;\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<a class=\"navbar-brand text-light\" href=\"#\" >H O T 차 박 지</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"hot-loaction-content-hs\"\r\n");
      out.write("				style=\"margin-bottom: 0px; margin-top: 10px;\">\r\n");
      out.write("				<div class=\"carousel\"\r\n");
      out.write("					data-flickity='{ \"cellAlign\": \"left\", \"contain\": true ,\r\n");
      out.write(" 									\"autoPlay\": 1200,\"pauseAutoPlayOnHover\": false,\r\n");
      out.write("									\"dragThreshold\": 10,\"imagesLoaded\": true,\r\n");
      out.write("									\"freeScroll\": true,\"wrapAround\": true}'>\r\n");
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<!--추천차박지  -->\r\n");
      out.write("	<div class=\"ccm-b-hs\" style=\"margin-top: 20px; margin-bottom: 45px;\">\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-expand-lg navbar navbar-dark bg-primary border rounded-4 border-4\"\r\n");
      out.write("			aria-label=\"Eighth navbar example\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand text-light\" href=\"#\">추 천 차 박 지</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div id=\"recommand-loaction-content-hs \">\r\n");
      out.write("			<div class=\"carousel\"\r\n");
      out.write("				data-flickity='{ \"cellAlign\": \"left\", \"contain\": true ,\r\n");
      out.write(" 									\"autoPlay\": 1200,\"pauseAutoPlayOnHover\": false,\r\n");
      out.write("									\"dragThreshold\": 10,\"imagesLoaded\": true,\r\n");
      out.write("									\"freeScroll\": true,\"wrapAround\": true}'>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<div id=\"hd\">\r\n");
      out.write("<div class=\"banner_slide\"> <!--바케성 0613 배너  -->\r\n");
      out.write("	<div class=\"card text-center\"> \r\n");
      out.write("		<div class=\"card-body\" >\r\n");
      out.write("			<a href=\"https://www.naver.com\">\r\n");
      out.write("				<img src=\"resources/images/banner1.PNG\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"card text-center\">\r\n");
      out.write("		<div class=\"card-body\" >\r\n");
      out.write("			<a href=\"https://www.naver.com\">\r\n");
      out.write("				<img src=\"resources/images/banner2.PNG\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"card text-center\">\r\n");
      out.write("		<div class=\"card-body\" >\r\n");
      out.write("			<a href=\"https://www.naver.com\">\r\n");
      out.write("				<img src=\"resources/images/banner3.PNG\" style=\"width:1870px; height:150px; padding:0px;\"/>\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\"\r\n");
      out.write("	style=\"padding-bottom: 0px; margin-top: 0px; padding-top: 0px;\">\r\n");
      out.write("	<p\r\n");
      out.write("		style=\"background-color: #2c3e50; color: #fff; margin-bottom: 0px;\">\r\n");
      out.write("		Copyright © 2022 <a href=\"#\">WITHCAR Co.</a> Ltd. All Rights Reserved.\r\n");
      out.write("		<br> Design: <a href=\"#\">WITHCAR DESIGN TEAM</a> <br> MADE\r\n");
      out.write("		BY: <a href=\"#\">WITHCAR TEAM</a>\r\n");
      out.write("	</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 바케성0613 배너 js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"></script> -->\r\n");
      out.write("<!--   <script src=\"resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<script src=\"resources/js/isotope.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/owl-carousel.js\"></script>\r\n");
      out.write("<script src=\"resources/js/lightbox.js\"></script>\r\n");
      out.write("<script src=\"resources/js/tabs.js\"></script>\r\n");
      out.write("<script src=\"resources/js/video.js\"></script>\r\n");
      out.write("<script src=\"resources/js/slick-slider.js\"></script>\r\n");
      out.write("<script src=\"resources/js/custom.js\"></script>	\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    \r\n");
      out.write("        //according to loftblog tut\r\n");
      out.write("        $('.nav li:first').addClass('active');\r\n");
      out.write("\r\n");
      out.write("        var showSection = function showSection(section, isAnimate) {\r\n");
      out.write("          var\r\n");
      out.write("          direction = section.replace(/#/, ''),\r\n");
      out.write("          reqSection = $('.section').filter('[data-section=\"' + direction + '\"]'),\r\n");
      out.write("          reqSectionPos = reqSection.offset().top - 0;\r\n");
      out.write("\r\n");
      out.write("          if (isAnimate) {\r\n");
      out.write("            $('body, html').animate({\r\n");
      out.write("              scrollTop: reqSectionPos },\r\n");
      out.write("            800);\r\n");
      out.write("          } else {\r\n");
      out.write("            $('body, html').scrollTop(reqSectionPos);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var checkSection = function checkSection() {\r\n");
      out.write("          $('.section').each(function () {\r\n");
      out.write("            var\r\n");
      out.write("            $this = $(this),\r\n");
      out.write("            topEdge = $this.offset().top - 80,\r\n");
      out.write("            bottomEdge = topEdge + $this.height(),\r\n");
      out.write("            wScroll = $(window).scrollTop();\r\n");
      out.write("            if (topEdge < wScroll && bottomEdge > wScroll) {\r\n");
      out.write("              var\r\n");
      out.write("              currentId = $this.data('section'),\r\n");
      out.write("              reqLink = $('a').filter('[href*=\\#' + currentId + ']');\r\n");
      out.write("              reqLink.closest('li').addClass('active').\r\n");
      out.write("              siblings().removeClass('active');\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {\r\n");
      out.write("          e.preventDefault();\r\n");
      out.write("          showSection($(this).attr('href'), true);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("          checkSection();\r\n");
      out.write("        });\r\n");
      out.write("        /*바케성 0613 배너추가  */\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $('.banner_slide').slick({\r\n");
      out.write("            	slide: 'div',		//슬라이드 되어야 할 태그 ex) div, li \r\n");
      out.write("				infinite : true, 	//무한 반복 옵션	 \r\n");
      out.write("				slidesToShow : 1,		// 한 화면에 보여질 컨텐츠 개수\r\n");
      out.write("				slidesToScroll : 1,		//스크롤 한번에 움직일 컨텐츠 개수\r\n");
      out.write("				speed : 2000,	 // 다음 버튼 누르고 다음 화면 뜨는데까지 걸리는 시간(ms)\r\n");
      out.write("				arrows : false, 		// 옆으로 이동하는 화살표 표시 여부\r\n");
      out.write("				dots : false, 		// 스크롤바 아래 점으로 페이지네이션 여부\r\n");
      out.write("				autoplay : true,			// 자동 스크롤 사용 여부\r\n");
      out.write("				autoplaySpeed : 3000, 		// 자동 스크롤 시 다음으로 넘어가는데 걸리는 시간 (ms)\r\n");
      out.write("				pauseOnHover : false,		// 슬라이드 이동	시 마우스 호버하면 슬라이더 멈추게 설정\r\n");
      out.write("				vertical : false,		// 세로 방향 슬라이드 옵션\r\n");
      out.write("				/* prevArrow : \"<button type='button' class='slick-prev'>Previous</button>\",		// 이전 화살표 모양 설정\r\n");
      out.write("				nextArrow : \"<button type='button' class='slick-next'>Next</button>\",		// 다음 화살표 모양 설정\r\n");
      out.write("				dotsClass : \"slick-dots\", 	//아래 나오는 페이지네이션(점) css class 지정 */\r\n");
      out.write("				draggable : true, 	//드래그 가능 여부 \r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/region/../top.jsp(113,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty mbdto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("	\r\n");
          out.write("							<li><a href=\"login.login\">로그인</a></li>\r\n");
          out.write("							<li><a href=\"sign.login\">회원가입</a></li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/region/../top.jsp(117,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mbdto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li><a href=\"logout.login\">로그아웃</a></li>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/region/regionHotLocList.jsp(16,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty hotList_Region}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<li class=\"list-group-item position-relative\"><img\r\n");
          out.write("					src=\"resources/images/sik.jpg\"\r\n");
          out.write("					class=\"img-responsive rounded-circle\"\r\n");
          out.write("					style=\"width: 107px; height: 107px;\">\r\n");
          out.write("					<div class=\"position-absolute top-50 start-50 translate-middle\">\r\n");
          out.write("						<strong>지도에서 마커를 클릭해주세요 ! </strong>\r\n");
          out.write("					</div></li>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/region/regionHotLocList.jsp(24,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hl_region");
      // /WEB-INF/views/region/regionHotLocList.jsp(24,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/region/regionHotLocList.jsp(24,11) '${hotList_Region}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hotList_Region}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				<li class=\"list-group-item position-relative\"><img\r\n");
            out.write("					src=\"resources/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hl_region.ccr_viewImage1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("					class=\"img-responsive rounded-circle\"\r\n");
            out.write("					style=\"width: 107px; height: 107px;\">\r\n");
            out.write("					<div class=\"position-absolute top-50 start-50 translate-middle\">\r\n");
            out.write("						<i class=\"bi bi-trophy-fill\" width=\"40\" height=\"40\" style=\"color:#ffc107;\"></i>\r\n");
            out.write("						<a href=\"regionView.region?ccr_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hl_region.ccr_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hl_region.ccr_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					</div></li>\r\n");
            out.write("\r\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/region/regionMainBottom.jsp(31,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("hotRegion");
      // /WEB-INF/views/region/regionMainBottom.jsp(31,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/region/regionMainBottom.jsp(31,5) '${hotRegionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hotRegionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			\r\n");
            out.write("						<a href=\"regionView.region?ccr_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotRegion.ccr_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("							<div class=\"carousel-cell\" style=\"width: 300px; height: 380px\">\r\n");
            out.write("								<div class=\"card\" style=\"width: 100%; height: 100%\">\r\n");
            out.write("									<img src=\"resources/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotRegion.ccr_viewImage1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("										class=\"card-img-top\" alt=\"...\">\r\n");
            out.write("									<div class=\"card-body\">\r\n");
            out.write("										<h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotRegion.ccr_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("										<hr>\r\n");
            out.write("										<p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotRegion.ccr_summary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</a>\r\n");
            out.write("\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/region/regionMainBottom.jsp(68,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("recommandRegion");
      // /WEB-INF/views/region/regionMainBottom.jsp(68,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/region/regionMainBottom.jsp(68,4) '${recommandRegionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recommandRegionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("					<a href=\"regionView.region?ccr_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recommandRegion.ccr_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("						<div class=\"carousel-cell\" style=\"width: 300px; height: 380px\">\r\n");
            out.write("							<div class=\"card\" style=\"width: 100%; height: 100%\">\r\n");
            out.write("								<img src=\"resources/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recommandRegion.ccr_viewImage1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("									class=\"card-img-top\" alt=\"...\">\r\n");
            out.write("								<div class=\"card-body\">\r\n");
            out.write("									<h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recommandRegion.ccr_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("									<hr>\r\n");
            out.write("									<p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recommandRegion.ccr_summary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					</a>\r\n");
            out.write("\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
