/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-13 02:46:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/WebDevelopment/git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CarCamping/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655811683348L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"TemplateMo\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>WithCar HomePage</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Additional CSS Files -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/fontawesome.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/templatemo-edu-meeting.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/owl.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/lightbox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/map_region.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/ghost.css\">\r\n");
      out.write("<style>\r\n");
      out.write("img, svg {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("   margin-left:15%;\r\n");
      out.write("   margin-right:15%;\r\n");
      out.write("}\r\n");
      out.write(".jb-box {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  margin: 0px auto;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".hoverLogo {\r\n");
      out.write("  position: absolute;\r\n");
      out.write(" left: 50%;\r\n");
      out.write("  top: 40%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hoverLogo #hoverLogoImage {\r\n");
      out.write("	width:0px; /*450 350 */\r\n");
      out.write("	height:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("	\r\n");
      out.write("<script src=\"resources/js/jquery.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $( document ).ready( function() {\r\n");
      out.write("    	$(\".jb-text #goMainButton\").click(function(){\r\n");
      out.write("    		  $( '.hoverLogo' ).fadeIn(3000);\r\n");
      out.write("    		  $('#hoverLogoImage').animate(\r\n");
      out.write("    		  	{width:'450px',height :'350px'},\r\n");
      out.write("    		  	3000,\r\n");
      out.write("    		  	function() {\r\n");
      out.write("    		  	  $( '.hoverLogo' ).fadeOut(3000);	    		\r\n");
      out.write("    		  	}\r\n");
      out.write("    	 		);\r\n");
      out.write("    	});\r\n");
      out.write("    });\r\n");
      out.write("    	      \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"padding-top: 0px;\">\r\n");
      out.write("   <div class=\"jb-box\">\r\n");
      out.write("      <header class=\"header-area header-sticky\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-12\">\r\n");
      out.write("                  <nav class=\"main-nav navbar-expand-lg navbar-dark shadow-5-strong\">\r\n");
      out.write("                     <!-- ***** Logo Start ***** -->\r\n");
      out.write("                     <a href=\"index.do\" class=\"logo\"> <img src=\"resources/images/withcar.png\" style=\"width: 170px;height: 70px;\"/></a>\r\n");
      out.write("                     <!-- ***** Logo End ***** -->\r\n");
      out.write("                     <!-- ***** Menu Start ***** -->\r\n");
      out.write("                     <ul class=\"nav\">\r\n");
      out.write("                     <!-- 처음들어갔을때 -->\r\n");
      out.write("                        <!--    요ㅕ걸롱!!!!!!!!!!!!!!!\r\n");
      out.write("                        <li><a href=\"홈페이지로\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-house-door-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                          <path d=\"M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z\"/>\r\n");
      out.write("                        </svg></a></li>\r\n");
      out.write("                        <li class=\"scroll-to-section\"><a href=\"회원가입으로\">회원가입</a></li>\r\n");
      out.write("                        <li><a href=\"로그인으로\">로그인</a></li>\r\n");
      out.write("                         -->\r\n");
      out.write("                        <!-- 로그인 시 ver 1-->\r\n");
      out.write("                         <!-- \r\n");
      out.write("                         <li><a href=\"홈페이지로\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-house-door-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                          <path d=\"M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z\"/>\r\n");
      out.write("                        </svg></a></li>\r\n");
      out.write("                        <li><a href=\"\">로그아웃</a></li>\r\n");
      out.write("                        <li><a href=\"\"> nickname... 마이페이지</a></li> -->\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- 로그인 시 ver 2 <====요걸로!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("                           <li class=\"has-sub\"><a href=\"javascript:void(0)\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-bell-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                          <path d=\"M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"sub-menu\">\r\n");
      out.write("                           \r\n");
      out.write("                              <li><a href=\"uesrAnnounce.admin\">공지사항</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                     \r\n");
      out.write("               \r\n");
      out.write("                     <!-- ***** Menu End ***** -->\r\n");
      out.write("                  </nav>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <video muted autoplay loop>\r\n");
      out.write("         <source src=\"resources/video/highway-loop.mp4\" type=\"video/mp4\">\r\n");
      out.write("      </video>\r\n");
      out.write("      <div class=\"hoverLogo\">\r\n");
      out.write("    	<img src=\"resources/images/123.png\" id=\"hoverLogoImage\" style=\" pointer-events: none; \"/>\r\n");
      out.write("  	  </div>\r\n");
      out.write("      <div class=\"jb-text\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"button-row\" id=\"goMainButton\">\r\n");
      out.write("				<div style=\"display: flex;\">\r\n");
      out.write("					<a title=\"차박지\" href=\"goRegion.region\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"display: flex;\">\r\n");
      out.write("					<a title=\"용품 \" href=\"goProduct.product\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <script>\r\n");
      out.write("        //according to loftblog tut\r\n");
      out.write("        $('.nav li:first').addClass('active');\r\n");
      out.write("\r\n");
      out.write("        var showSection = function showSection(section, isAnimate) {\r\n");
      out.write("          var\r\n");
      out.write("          direction = section.replace(/#/, ''),\r\n");
      out.write("          reqSection = $('.section').filter('[data-section=\"' + direction + '\"]'),\r\n");
      out.write("          reqSectionPos = reqSection.offset().top - 0;\r\n");
      out.write("\r\n");
      out.write("          if (isAnimate) {\r\n");
      out.write("            $('body, html').animate({\r\n");
      out.write("              scrollTop: reqSectionPos },\r\n");
      out.write("            800);\r\n");
      out.write("          } else {\r\n");
      out.write("            $('body, html').scrollTop(reqSectionPos);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var checkSection = function checkSection() {\r\n");
      out.write("          $('.section').each(function () {\r\n");
      out.write("            var\r\n");
      out.write("            $this = $(this),\r\n");
      out.write("            topEdge = $this.offset().top - 80,\r\n");
      out.write("            bottomEdge = topEdge + $this.height(),\r\n");
      out.write("            wScroll = $(window).scrollTop();\r\n");
      out.write("            if (topEdge < wScroll && bottomEdge > wScroll) {\r\n");
      out.write("              var\r\n");
      out.write("              currentId = $this.data('section'),\r\n");
      out.write("              reqLink = $('a').filter('[href*=\\#' + currentId + ']');\r\n");
      out.write("              reqLink.closest('li').addClass('active').\r\n");
      out.write("              siblings().removeClass('active');\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {\r\n");
      out.write("          e.preventDefault();\r\n");
      out.write("          showSection($(this).attr('href'), true);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("          checkSection();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("	  <div class=\"footer\" style=\"padding-bottom: 0px;margin-top: 0px;padding-top: 0px;\">\r\n");
      out.write("      <p style=\" background-color:#2c3e50; color:#fff;margin-bottom: 0px;\">Copyright © 2022 <a href=\"#\">WITHCAR Co.</a> Ltd. All Rights Reserved. \r\n");
      out.write("          <br>\r\n");
      out.write("          Design: <a href=\"#\">WITHCAR DESIGN TEAM</a>\r\n");
      out.write("          <br>\r\n");
      out.write("          MADE BY: <a href=\"#\">WITHCAR TEAM</a>\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--/.section -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<!-- Bootstrap JavaScript -->\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("   \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("   <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resources/js/isotope.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/owl-carousel.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/lightbox.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/tabs.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/video.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/slick-slider.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/custom.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("        //according to loftblog tut\r\n");
      out.write("        $('.nav li:first').addClass('active');\r\n");
      out.write("\r\n");
      out.write("        var showSection = function showSection(section, isAnimate) {\r\n");
      out.write("          var\r\n");
      out.write("          direction = section.replace(/#/, ''),\r\n");
      out.write("          reqSection = $('.section').filter('[data-section=\"' + direction + '\"]'),\r\n");
      out.write("          reqSectionPos = reqSection.offset().top - 0;\r\n");
      out.write("\r\n");
      out.write("          if (isAnimate) {\r\n");
      out.write("            $('body, html').animate({\r\n");
      out.write("              scrollTop: reqSectionPos },\r\n");
      out.write("            800);\r\n");
      out.write("          } else {\r\n");
      out.write("            $('body, html').scrollTop(reqSectionPos);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var checkSection = function checkSection() {\r\n");
      out.write("          $('.section').each(function () {\r\n");
      out.write("            var\r\n");
      out.write("            $this = $(this),\r\n");
      out.write("            topEdge = $this.offset().top - 80,\r\n");
      out.write("            bottomEdge = topEdge + $this.height(),\r\n");
      out.write("            wScroll = $(window).scrollTop();\r\n");
      out.write("            if (topEdge < wScroll && bottomEdge > wScroll) {\r\n");
      out.write("              var\r\n");
      out.write("              currentId = $this.data('section'),\r\n");
      out.write("              reqLink = $('a').filter('[href*=\\#' + currentId + ']');\r\n");
      out.write("              reqLink.closest('li').addClass('active').\r\n");
      out.write("              siblings().removeClass('active');\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {\r\n");
      out.write("          e.preventDefault();\r\n");
      out.write("          showSection($(this).attr('href'), true);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("          checkSection();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(108,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty mbdto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("                        <li class=\"has-sub\"><a href=\"javascript:void(0)\">\r\n");
          out.write("                           사용자\r\n");
          out.write("                           <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" fill=\"currentColor\" class=\"bi bi-person-lines-fill\" viewBox=\"0 0 16 16\" style=\"margin-bottom: 2.5;\">\r\n");
          out.write("                             <path d=\"M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z\"/>\r\n");
          out.write("                           </svg>\r\n");
          out.write("                           </a>\r\n");
          out.write("                           \r\n");
          out.write("                           <ul class=\"sub-menu\">\r\n");
          out.write("                           \r\n");
          out.write("                              <li><a href=\"login.login\">로그인</a></li>\r\n");
          out.write("                              <li><a href=\"sign.login\">회원가입</a></li>\r\n");
          out.write("\r\n");
          out.write("                           </ul>\r\n");
          out.write("                        </li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(127,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mbdto}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                           <li class=\"has-sub\"><a href=\"javascript:void(0)\">\r\n");
          out.write("                           사용자\r\n");
          out.write("                           <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" fill=\"currentColor\" class=\"bi bi-person-lines-fill\" viewBox=\"0 0 16 16\" style=\"margin-bottom: 2.5;\">\r\n");
          out.write("                             <path d=\"M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z\"/>\r\n");
          out.write("                           </svg>\r\n");
          out.write("                           </a>\r\n");
          out.write("                           \r\n");
          out.write("                           <ul class=\"sub-menu\">\r\n");
          out.write("                           \r\n");
          out.write("                              <li><a href=\"logout.login\">로그아웃</a></li>\r\n");
          out.write("                              <li><a href=\"myPageProfile.myPage\">마이페이지</a></li>\r\n");
          out.write("                           </ul>\r\n");
          out.write("                        </li>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
